### ISSUE TITLE
DirectX support

### ISSUE THREAD

**Issue by dominota** [endlesstravel/DearLoveGUI#1]
Thank you for greate library. can you add support for DirectX?

**Comment by endlesstravel** [comment]
sorry, this library is imgui support for `LoveSharp` so i have no idea to support directx. 
but you  can use `https://github.com/amerkoleci/Vortice.Windows` with `https://github.com/YaakovDavis/VorticeImGui` 😃

**Comment by dominota** [comment]
Thank you so much @endlesstravel
